runtime: go114

env_variables:
  DOMAIN: "crowdspec.dev"
  DEV_ENV: "appengine"
  MAINTENANCE_MODE: "false"
  DB_HOST: "/cloudsql/crowdspec-dev:northamerica-northeast1:crowdspec-dev"
  DB_NAME: "crowdspec"
  DB_USER: "postgres"
  DB_PASS_SECRET: "projects/178253280892/secrets/DB_PASS"
  ADMIN_USER_ID: "1"
  RECAPTCHA_SITE_KEY: "6Lfg_8UZAAAAABHHDDBZfQVED-glpgYUjQjwjpb0"
  RECAPTCHA_SECRET: "projects/178253280892/secrets/RECAPTCHA"
  MAILJET_API_KEY: "b0334490baa0138d74375c16998277a0"
  MAILJET_SECRET: "projects/178253280892/secrets/MAILJET_SECRET_KEY"
  YOUTUBE_API_KEY: "AIzaSyDF6SEQrNQZWXmLjO-8fNX5qdwnpmui7yE"
  HTTP_CLIENT_REFERER: "https://crowdspec.dev"
  VERSION_STAMP: "202102160923"

handlers:
- url: /css
  static_dir: css
  secure: always
- url: /js
  static_dir: js
  secure: always
- url: /img
  static_dir: img
  secure: always
- url: /.*
  script: auto
  secure: always
